### PR TITLE
updated jlucido professional page

### PR DESCRIPTION
**Pull request by jlucido2**

### CODE REVIEW

**Comment by jlucido2** [comment]
@mwernimont - For some reason it won't let me assign anyone to this, but can you review?

**Comment by cschroed-usgs** [comment]
@jlucido2 -- you weren't able to assign Marty earlier because of a team permissions issue on this repo. I've fixed that, so you should be able to assign to anyone in the CIDA Team in the future.

**Comment by jlucido2** [comment]
Thanks @cschroed-usgs!

**Comment by jlucido2** [comment]
@jread-usgs after merging does something have to happen to update the website?

**Comment by mwarren-USGS** [comment]
Not sure why I am a watcher on this ticket. Am I an admin of the JIRA board
for this project now?

On Wed, Dec 16, 2015 at 1:42 PM, Jessica Lucido <notifications@github.com>
wrote:

> @jread-usgs <https://github.com/jread-usgs> after merging does something
> have to happen to update the website?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-CIDA/cida_website/pull/7#issuecomment-165222623>.
>



-- 
Meredith Pavlick Warren
U.S. Geological Survey
Office of Water Information
Center for Integrated Data Analytics
8505 Research Way
Middleton, WI  53562
608-821-3878

**Pull request merged**
